In [1]:
a = [0, 1, 2, 3, 4]

In [2]:
import numpy as np

In [3]:
a = np.array(a)
a

array([0, 1, 2, 3, 4])

In [4]:
a.dtype

dtype('int64')

In [5]:
a = np.array([0.4, 1.2, 2.4, 3.6, 4.3])

In [6]:
a.dtype

dtype('float64')

In [7]:
type(a)

numpy.ndarray

In [8]:
c = np.array([20, 1, 2, 3, 5])

In [9]:
c[0] = 100

In [10]:
c

array([100,   1,   2,   3,   5])

In [11]:
c[1:4]

array([1, 2, 3])

In [12]:
c[3:5] = 300, 400

In [13]:
c

array([100,   1,   2, 300, 400])

In [14]:
select = [0, 2, 3]

In [15]:
d = c[select]
d

array([100,   2, 300])

In [16]:
c[select] = 1000000

In [17]:
c

array([1000000,       1, 1000000, 1000000,     400])

In [19]:
a = np.array([0, 1, 2, 3, 4])

In [20]:
a.size

5

In [21]:
a.ndim

1

In [22]:
a.shape

(5,)

In [23]:
Mean = a.mean()
Mean

np.float64(2.0)

In [24]:
Median = np.median(a)
Median

np.float64(2.0)

In [25]:
np.std(a)

np.float64(1.4142135623730951)

In [26]:
a.max()

np.int64(4)

In [27]:
a.min()

np.int64(0)

In [28]:
u = np.array([10, 1, 4])

In [29]:
v =  np.array([1, 10, 5])

In [30]:
z = u + v
z

array([11, 11,  9])

In [31]:
y = 2 * z
y

array([22, 22, 18])

In [32]:
u * v

array([10, 10, 20])

In [33]:
u - v

array([ 9, -9, -1])

In [34]:
u / v

array([10. ,  0.1,  0.8])

In [35]:
u % v

array([0, 1, 4])

In [36]:
np.dot(u, v)

np.int64(40)

In [37]:
u + 1

array([11,  2,  5])

In [38]:
x = [0, np.pi/2, np.pi]

In [39]:
x = np.sin(x)
x

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [44]:
array = np.linspace(-2, 2, 5) # (start, stop, number of elements)
array

array([-2., -1.,  0.,  1.,  2.])

In [45]:
x = np.linspace(0, 2*np.pi, 5)
x

array([0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531])

In [47]:
y = np.sin(x)
y

array([ 0.0000000e+00,  1.0000000e+00,  1.2246468e-16, -1.0000000e+00,
       -2.4492936e-16])

In [48]:
a = np.array([1, 0])
b = np.array([0, 1])
c = np.dot(a, b)
c

np.int64(0)

In [50]:
a = np.array([1, 1])
b = np.array([0, 1])
c = np.dot(a, b)
c

np.int64(1)

# 2 Dim Array

In [53]:
Ar = np.array([[11, 12, 13],
                  [21, 22, 23],
                  [31, 32, 33]])
Ar

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [55]:
Ar.ndim

2

In [56]:
Ar.shape

(3, 3)

In [57]:
Ar.size

9

In [60]:
Ar[1, 2]

np.int64(23)

In [61]:
Ar[1][2]

np.int64(23)

In [62]:
Ar[0, 0:2]

array([11, 12])

In [64]:
Ar[1:3, 2]

array([23, 33])

In [66]:
X = np.array([[1, 0],
              [0, 1]])
Y = np.array([[2, 1],
              [1, 2]])
Z = X + Y
Z

array([[3, 1],
       [1, 3]])

In [70]:
X * Y

array([[2, 0],
       [0, 2]])

In [71]:
X @ Y

array([[2, 1],
       [1, 2]])

In [74]:
A = np.array([[0, 1, 1],
               [1, 0, 1]])
B = np.array([[1, 1],
              [1, 1],
              [-1, 1]])
C = A @ B
C

array([[0, 2],
       [0, 2]])

In [76]:
np.dot(A, B)

array([[0, 2],
       [0, 2]])

In [78]:
transpose = B.T
transpose

array([[ 1,  1, -1],
       [ 1,  1,  1]])

In [81]:
X = np.array([[1, 2],
     [3, 4]])
X.T



array([[1, 3],
       [2, 4]])