# 1 - Text Cleaning with NLTK

In [77]:
import nltk
nltk.download("punkt")
nltk.download("punkt_tab")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [78]:
import re
import nltk
nltk.download("stopwords")
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [79]:
from nltk.tokenize import word_tokenize

In [80]:
def lower_case(text):
  text = text.lower()
  return text

In [81]:
def remove_punctuation(text):
  punctuation_pattern = r'[^\w\s]'
  text_cleaned = re.sub(punctuation_pattern, '', text)
  return text_cleaned

In [82]:
def remove_stopwords(text, language):
  stop_words = set(stopwords.words(language))
  text = text.lower()
  words_token = text.split()
  filtered_text = [word for word in words_token if word.lower() not in stop_words]
  filtered_text = " ".join(filtered_text)
  return filtered_text

In [83]:
def word_token_conv(text):
  sample_text = text
  token = word_tokenize(sample_text)
  return token

In [84]:
file_path = '/content/Example_dataset_NLP.txt'
with open(file_path, 'r', encoding='utf-8') as file:
    text_data = file.read()

In [85]:
text_data

'Fellow-Citizens of the Senate and of the House of Representatives:\nAmong the vicissitudes incident to life no event could have filled me with greater anxieties than that of which the notification was transmitted by your order, and received on the 14th day of the present month. On the one hand, I was summoned by my Country, whose voice I can never hear but with veneration and love, from a retreat which I had chosen with the fondest predilection, and, in my flattering hopes, with an immutable decision, as the asylum of my declining years -- a retreat which was rendered every day more necessary as well as more dear to me by the addition of habit to inclination, and of frequent interruptions in my health to the gradual waste committed on it by time. On the other hand, the magnitude and difficulty of the trust to which the voice of my country called me, being sufficient to awaken in the wisest and most experienced of her citizens a distrustful scrutiny into his qualifications, could not b

## Lower Case

In [86]:
cleaned_data = lower_case(text_data)
cleaned_data

'fellow-citizens of the senate and of the house of representatives:\namong the vicissitudes incident to life no event could have filled me with greater anxieties than that of which the notification was transmitted by your order, and received on the 14th day of the present month. on the one hand, i was summoned by my country, whose voice i can never hear but with veneration and love, from a retreat which i had chosen with the fondest predilection, and, in my flattering hopes, with an immutable decision, as the asylum of my declining years -- a retreat which was rendered every day more necessary as well as more dear to me by the addition of habit to inclination, and of frequent interruptions in my health to the gradual waste committed on it by time. on the other hand, the magnitude and difficulty of the trust to which the voice of my country called me, being sufficient to awaken in the wisest and most experienced of her citizens a distrustful scrutiny into his qualifications, could not b

## Remove Punctuation

In [87]:
cleaned_data = remove_punctuation(cleaned_data)
cleaned_data

'fellowcitizens of the senate and of the house of representatives\namong the vicissitudes incident to life no event could have filled me with greater anxieties than that of which the notification was transmitted by your order and received on the 14th day of the present month on the one hand i was summoned by my country whose voice i can never hear but with veneration and love from a retreat which i had chosen with the fondest predilection and in my flattering hopes with an immutable decision as the asylum of my declining years  a retreat which was rendered every day more necessary as well as more dear to me by the addition of habit to inclination and of frequent interruptions in my health to the gradual waste committed on it by time on the other hand the magnitude and difficulty of the trust to which the voice of my country called me being sufficient to awaken in the wisest and most experienced of her citizens a distrustful scrutiny into his qualifications could not but overwhelm with 

## Remove Stop Words

In [88]:
cleaned_data = remove_stopwords(cleaned_data, "english")
cleaned_data

'fellowcitizens senate house representatives among vicissitudes incident life event could filled greater anxieties notification transmitted order received 14th day present month one hand summoned country whose voice never hear veneration love retreat chosen fondest predilection flattering hopes immutable decision asylum declining years retreat rendered every day necessary well dear addition habit inclination frequent interruptions health gradual waste committed time hand magnitude difficulty trust voice country called sufficient awaken wisest experienced citizens distrustful scrutiny qualifications could overwhelm despondence one inheriting inferior endowments nature unpracticed duties civil administration ought peculiarly conscious deficiencies conflict emotions dare aver faithful study collect duty appreciation every circumstance might affected dare hope executing task much swayed grateful remembrance former instances affectionate sensibility transcendent proof confidence fellow citi

## Word Tokenization

In [89]:
cleaned_data_list = word_tokenize(cleaned_data)
print(len(cleaned_data_list))
print(cleaned_data_list)


139
['fellowcitizens', 'senate', 'house', 'representatives', 'among', 'vicissitudes', 'incident', 'life', 'event', 'could', 'filled', 'greater', 'anxieties', 'notification', 'transmitted', 'order', 'received', '14th', 'day', 'present', 'month', 'one', 'hand', 'summoned', 'country', 'whose', 'voice', 'never', 'hear', 'veneration', 'love', 'retreat', 'chosen', 'fondest', 'predilection', 'flattering', 'hopes', 'immutable', 'decision', 'asylum', 'declining', 'years', 'retreat', 'rendered', 'every', 'day', 'necessary', 'well', 'dear', 'addition', 'habit', 'inclination', 'frequent', 'interruptions', 'health', 'gradual', 'waste', 'committed', 'time', 'hand', 'magnitude', 'difficulty', 'trust', 'voice', 'country', 'called', 'sufficient', 'awaken', 'wisest', 'experienced', 'citizens', 'distrustful', 'scrutiny', 'qualifications', 'could', 'overwhelm', 'despondence', 'one', 'inheriting', 'inferior', 'endowments', 'nature', 'unpracticed', 'duties', 'civil', 'administration', 'ought', 'peculiarly',

## Conclusion

The data is cleaned by following methods:      
Firstly, the dataset is lowerized, then the stopwords are removed. After that, I remove punctuation. And in the last, the dataset is tokenized using word tokenization.

# 2 - Image Data Reduction

In [94]:
import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

In [96]:
input_layer = tf.keras.layers.Input(shape=(28, 28, 1))

In [97]:
model = tf.keras.Sequential([
    input_layer,
    layers.Conv2D(filters=10, kernel_size=(3,3), activation="relu"),
    layers.MaxPooling2D(),
    layers.Flatten(),
    layers.Dense(10, activation="softmax")
])

### Manual 2x2 Max Pooling Function

This function `max_pooling_2x2` takes a 2D NumPy array (representing a feature map) and performs a 2x2 max pooling operation. For each non-overlapping 2x2 block in the input, it selects the maximum value, effectively reducing the spatial dimensions of the feature map while retaining the most prominent features.

In [104]:
import numpy as np

def max_pooling_2x2(feature_map):
  h, w = feature_map.shape
  if h % 2 != 0 or w % 2 != 0:
    raise ValueError("Feature map dimensions must be even for 2x2 max pooling.")
  output_h = h // 2
  output_w = w // 2
  pooled_map = np.zeros((output_h, output_w))
  for i in range(output_h):
      for j in range(output_w):
        block = feature_map[i*2:(i*2)+2, j*2:(j*2)+2]
        pooled_map[i, j] = np.max(block)
  return pooled_map

In [102]:
sample_feature_map = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

print("Original Feature Map:")
print(sample_feature_map)

# Apply the manual 2x2 max pooling
pooled_result = max_pooling_2x2(sample_feature_map)

print("\nPooled Feature Map (2x2 max pooling):")
print(pooled_result)

Original Feature Map:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Pooled Feature Map (2x2 max pooling):
[[ 6.  8.]
 [14. 16.]]


# 3 - Lexical Analysis

In [90]:
nltk.download("tagsets_json")

[nltk_data] Downloading package tagsets_json to /root/nltk_data...
[nltk_data]   Package tagsets_json is already up-to-date!


True

In [91]:
nltk.download('averaged_perceptron_tagger')
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!


True

In [92]:
word = cleaned_data_list
pos_tags = nltk.pos_tag(word)
print("")
print("POS Tags\n", pos_tags, "\n")

for word, tag in pos_tags:
    print(nltk.help.upenn_tagset(tagpattern=tag))


POS Tags
 [('fellowcitizens', 'NNS'), ('senate', 'VBP'), ('house', 'NN'), ('representatives', 'NNS'), ('among', 'IN'), ('vicissitudes', 'NNS'), ('incident', 'JJ'), ('life', 'NN'), ('event', 'NN'), ('could', 'MD'), ('filled', 'VB'), ('greater', 'JJR'), ('anxieties', 'NNS'), ('notification', 'NN'), ('transmitted', 'VBD'), ('order', 'NN'), ('received', 'VBD'), ('14th', 'CD'), ('day', 'NN'), ('present', 'JJ'), ('month', 'NN'), ('one', 'CD'), ('hand', 'NN'), ('summoned', 'VBD'), ('country', 'NN'), ('whose', 'WP$'), ('voice', 'NN'), ('never', 'RB'), ('hear', 'JJ'), ('veneration', 'NN'), ('love', 'IN'), ('retreat', 'NN'), ('chosen', 'VBN'), ('fondest', 'JJS'), ('predilection', 'NN'), ('flattering', 'VBG'), ('hopes', 'NNS'), ('immutable', 'JJ'), ('decision', 'NN'), ('asylum', 'IN'), ('declining', 'VBG'), ('years', 'NNS'), ('retreat', 'RB'), ('rendered', 'VBD'), ('every', 'DT'), ('day', 'NN'), ('necessary', 'JJ'), ('well', 'RB'), ('dear', 'JJ'), ('addition', 'NN'), ('habit', 'NN'), ('inclinati

## Conclusion

The tokens are tagged with their associated Part of Speech(POS).